/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;
import java.util.ArrayList;
class AppTest {
    Factorizer factorizer;
    @BeforeEach
    public void setUp() {
        factorizer = new Factorizer();
    }

    @Test
    public void testFactorial() {
        ArrayList<Integer> testArr = new ArrayList<>();
        testArr.add(1);
        testArr.add(2);
        testArr.add(4);
        testArr.add(8);
        testArr.add(16);
        assertEquals(factorizer.factorize(16),testArr);
    }
}
