/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.ArrayList;
import java.util.Scanner;
public class App {
   public static void main(String[] args) {
    Factorizer factorizer = new Factorizer();
        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter a number: ");
        int userInput = scanner.nextInt();

        ArrayList<Integer> responseArray = factorizer.factorize(userInput);

        System.out.println("Factors of " + userInput+ " : " +responseArray);
        scanner.close();
   }
}
